import { Product } from "./data";

// Productos de prueba mejorados con balance por categorías y sistema de peso/gramaje
export const enhancedTestProducts: Product[] = [
  // PRODUCTOS FALTANTES - LÁCTEOS (CREMA)
  {
    id: "crema-para-batir-250ml",
    name: "Crema para Batir 250ml",
    price: 25,
    category: "lacteos-huevos",
    subcategory: "crema-cocinar",
    aisle: "Pasillo 4",
    image: "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Crema+Batir",
    description: "Crema para batir, ideal para postres",
    inStock: true,
    stock: 45,
    brand: "Lala",
    tags: ["crema", "batir", "postres", "lácteo"],
    rating: 4.6,
    reviewCount: 120,
    deliveryTime: "15-20 min",
    unit: "pieza",
    sellByWeight: false,
  },
  {
    id: "crema-espesa-500ml",
    name: "Crema Espesa para Cocinar 500ml",
    price: 35,
    category: "lacteos-huevos",
    subcategory: "crema-cocinar",
    aisle: "Pasillo 4", 
    image: "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Crema+Cocinar",
    description: "Crema espesa ideal para salsas y guisos",
    inStock: true,
    stock: 38,
    brand: "Nestle",
    tags: ["crema", "cocinar", "salsas", "espesa"],
    rating: 4.7,
    reviewCount: 89,
    deliveryTime: "15-20 min",
    unit: "pieza",
    sellByWeight: false,
  },
  {
    id: "crema-acida-250g",
    name: "Crema Ácida 250g",
    price: 22,
    category: "lacteos-huevos",
    subcategory: "crema-cocinar",
    aisle: "Pasillo 4",
    image: "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Crema+Acida",
    description: "Crema ácida para nachos y botanas",
    inStock: true,
    stock: 52,
    brand: "Philadelphia",
    tags: ["crema", "ácida", "nachos", "botanas"],
    rating: 4.5,
    reviewCount: 76,
    deliveryTime: "15-20 min",
    unit: "gramo",
    sellByWeight: true,
  },
  {
    id: "crema-chantilly-200ml",
    name: "Crema Chantilly Lista 200ml",
    price: 18,
    category: "lacteos-huevos",
    subcategory: "crema-cocinar",
    aisle: "Pasillo 4",
    image: "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Chantilly",
    description: "Crema chantilly lista para usar",
    inStock: true,
    stock: 30,
    brand: "Media Crema",
    tags: ["chantilly", "lista", "postres", "dulce"],
    rating: 4.4,
    reviewCount: 65,
    deliveryTime: "15-20 min",
    unit: "pieza",
    sellByWeight: false,
  },
  {
    id: "media-crema-500ml",
    name: "Media Crema 500ml",
    price: 28,
    category: "lacteos-huevos", 
    subcategory: "crema-cocinar",
    aisle: "Pasillo 4",
    image: "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Media+Crema",
    description: "Media crema para café y repostería",
    inStock: true,
    stock: 42,
    brand: "Nestle",
    tags: ["media", "crema", "café", "repostería"],
    rating: 4.8,
    reviewCount: 145,
    deliveryTime: "15-20 min",
    unit: "pieza",
    sellByWeight: false,
  },
  {
    id: "crema-doble-300ml",
    name: "Crema Doble 300ml",
    price: 32,
    category: "lacteos-huevos",
    subcategory: "crema-cocinar", 
    aisle: "Pasillo 4",
    image: "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Crema+Doble",
    description: "Crema doble extra espesa para chef",
    inStock: true,
    stock: 25,
    brand: "Chef",
    tags: ["crema", "doble", "espesa", "premium"],
    rating: 4.9,
    reviewCount: 92,
    deliveryTime: "15-20 min",
    unit: "pieza",
    sellByWeight: false,
  },

  // PRODUCTOS FALTANTES - CONGELADOS (POSTRES)
  {
    id: "paletas-helado-variadas",
    name: "Paletas de Helado Variadas 6pz",
    price: 45,
    category: "congelados",
    subcategory: "postres-congelados",
    aisle: "Pasillo 6",
    image: "https://via.placeholder.com/400x300/87CEEB/FFFFFF?text=Paletas+Helado",
    description: "Paletas de helado de diferentes sabores",
    inStock: true,
    stock: 35,
    brand: "Holanda",
    tags: ["paletas", "helado", "variadas", "frutal"],
    rating: 4.7,
    reviewCount: 156,
    deliveryTime: "15-20 min",
    unit: "paquete",
    sellByWeight: false,
  },
  {
    id: "gelatina-congelada-fresa",
    name: "Gelatina Congelada de Fresa 500g",
    price: 28,
    category: "congelados",
    subcategory: "postres-congelados",
    aisle: "Pasillo 6",
    image: "https://via.placeholder.com/400x300/87CEEB/FFFFFF?text=Gelatina+Fresa",
    description: "Gelatina de fresa lista para consumir",
    inStock: true,
    stock: 22,
    brand: "D'Gari",
    tags: ["gelatina", "fresa", "postre", "frío"],
    rating: 4.3,
    reviewCount: 78,
    deliveryTime: "15-20 min", 
    unit: "gramo",
    sellByWeight: true,
  },
  {
    id: "pay-congelado-manzana",
    name: "Pay de Manzana Congelado",
    price: 65,
    category: "congelados",
    subcategory: "postres-congelados",
    aisle: "Pasillo 6",
    image: "https://via.placeholder.com/400x300/87CEEB/FFFFFF?text=Pay+Manzana",
    description: "Pay de manzana congelado para hornear",
    inStock: true,
    stock: 15,
    brand: "Sara Lee",
    tags: ["pay", "manzana", "congelado", "hornear"],
    rating: 4.8,
    reviewCount: 94,
    deliveryTime: "15-20 min",
    unit: "pieza",
    sellByWeight: false,
  },

  // PRODUCTOS FALTANTES - CONGELADOS (PIZZA)
  {
    id: "pizza-pepperoni-familiar",
    name: "Pizza Pepperoni Familiar Congelada",
    price: 85,
    category: "congelados",
    subcategory: "pizza-congelada",
    aisle: "Pasillo 6",
    image: "https://via.placeholder.com/400x300/87CEEB/FFFFFF?text=Pizza+Pepperoni",
    description: "Pizza familiar de pepperoni lista para hornear",
    inStock: true,
    stock: 18,
    brand: "DiGiorno",
    tags: ["pizza", "pepperoni", "familiar", "congelada"],
    rating: 4.6,
    reviewCount: 203,
    deliveryTime: "15-20 min",
    unit: "pieza", 
    sellByWeight: false,
  },
  {
    id: "pizza-vegetariana-personal",
    name: "Pizza Vegetariana Personal Congelada",
    price: 35,
    category: "congelados",
    subcategory: "pizza-congelada",
    aisle: "Pasillo 6",
    image: "https://via.placeholder.com/400x300/87CEEB/FFFFFF?text=Pizza+Vegetariana",
    description: "Pizza personal vegetariana congelada",
    inStock: true,
    stock: 25,
    brand: "Amy's",
    tags: ["pizza", "vegetariana", "personal", "saludable"],
    rating: 4.4,
    reviewCount: 127,
    deliveryTime: "15-20 min",
    unit: "pieza",
    sellByWeight: false,
  },

  // PRODUCTOS FALTANTES - ABARROTES (SAL Y ESPECIAS)
  {
    id: "sal-mesa-refinada-1kg",
    name: "Sal de Mesa Refinada 1kg",
    price: 12,
    category: "abarrotes-basicos",
    subcategory: "sal-especias",
    aisle: "Pasillo 7", 
    image: "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Sal+Mesa",
    description: "Sal refinada de mesa para uso diario",
    inStock: true,
    stock: 80,
    brand: "La Fina",
    tags: ["sal", "mesa", "refinada", "básico"],
    rating: 4.2,
    reviewCount: 45,
    deliveryTime: "15-20 min",
    unit: "kg",
    sellByWeight: true,
  },
  {
    id: "pimienta-negra-molida-50g",
    name: "Pimienta Negra Molida 50g",
    price: 25,
    category: "abarrotes-basicos",
    subcategory: "sal-especias",
    aisle: "Pasillo 7",
    image: "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Pimienta+Negra",
    description: "Pimienta negra molida premium",
    inStock: true,
    stock: 35,
    brand: "McCormick",
    tags: ["pimienta", "negra", "molida", "especias"],
    rating: 4.7,
    reviewCount: 89,
    deliveryTime: "15-20 min",
    unit: "gramo",
    sellByWeight: true,
  },
  {
    id: "oregano-seco-20g",
    name: "Orégano Seco 20g",
    price: 18,
    category: "abarrotes-basicos",
    subcategory: "sal-especias",
    aisle: "Pasillo 7",
    image: "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Oregano",
    description: "Orégano seco para sazonar comidas",
    inStock: true,
    stock: 42,
    brand: "McCormick",
    tags: ["orégano", "seco", "hierba", "sazonador"],
    rating: 4.5,
    reviewCount: 67,
    deliveryTime: "15-20 min",
    unit: "gramo", 
    sellByWeight: true,
  },
  {
    id: "comino-molido-30g",
    name: "Comino Molido 30g",
    price: 22,
    category: "abarrotes-basicos",
    subcategory: "sal-especias",
    aisle: "Pasillo 7",
    image: "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Comino",
    description: "Comino molido para guisos y carnes",
    inStock: true,
    stock: 38,
    brand: "McCormick",
    tags: ["comino", "molido", "guisos", "carnes"],
    rating: 4.6,
    reviewCount: 54,
    deliveryTime: "15-20 min",
    unit: "gramo",
    sellByWeight: true,
  },
  {
    id: "paprika-dulce-40g",
    name: "Paprika Dulce 40g",
    price: 28,
    category: "abarrotes-basicos",
    subcategory: "sal-especias", 
    aisle: "Pasillo 7",
    image: "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Paprika",
    description: "Paprika dulce para color y sabor",
    inStock: true,
    stock: 30,
    brand: "McCormick",
    tags: ["paprika", "dulce", "color", "sabor"],
    rating: 4.4,
    reviewCount: 71,
    deliveryTime: "15-20 min",
    unit: "gramo",
    sellByWeight: true,
  },
  {
    id: "ajo-en-polvo-60g",
    name: "Ajo en Polvo 60g",
    price: 20,
    category: "abarrotes-basicos",
    subcategory: "sal-especias",
    aisle: "Pasillo 7",
    image: "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Ajo+Polvo",
    description: "Ajo deshidratado en polvo",
    inStock: true,
    stock: 45,
    brand: "McCormick",
    tags: ["ajo", "polvo", "deshidratado", "sazonador"],
    rating: 4.3,
    reviewCount: 82,
    deliveryTime: "15-20 min",
    unit: "gramo",
    sellByWeight: true,
  },
  {
    id: "canela-molida-25g",
    name: "Canela Molida 25g",
    price: 24,
    category: "abarrotes-basicos",
    subcategory: "sal-especias",
    aisle: "Pasillo 7",
    image: "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Canela",
    description: "Canela molida para postres y bebidas",
    inStock: true,
    stock: 40,
    brand: "McCormick",
    tags: ["canela", "molida", "postres", "bebidas"],
    rating: 4.8,
    reviewCount: 96,
    deliveryTime: "15-20 min",
    unit: "gramo",
    sellByWeight: true,
  },
  {
    id: "curry-en-polvo-35g",
    name: "Curry en Polvo 35g",
    price: 32,
    category: "abarrotes-basicos",
    subcategory: "sal-especias",
    aisle: "Pasillo 7",
    image: "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Curry",
    description: "Mezcla de curry en polvo oriental",
    inStock: true,
    stock: 25,
    brand: "McCormick",
    tags: ["curry", "polvo", "oriental", "picante"],
    rating: 4.5,
    reviewCount: 63,
    deliveryTime: "15-20 min",
    unit: "gramo",
    sellByWeight: true,
  },

  // PRODUCTOS CON SISTEMAS DE PESO AVANZADOS
  {
    id: "carne-molida-especial-kg",
    name: "Carne Molida Especial",
    price: 180,
    category: "carniceria-cremeria",
    subcategory: "carnes-rojas",
    aisle: "Pasillo 3",
    image: "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Carne+Molida",
    description: "Carne molida especial 80/20, precio por kg",
    inStock: true,
    stock: 50, // kg disponibles
    brand: "Carnicería Premium",
    tags: ["carne", "molida", "fresca", "kg"],
    rating: 4.9,
    reviewCount: 234,
    deliveryTime: "15-20 min",
    unit: "kg",
    sellByWeight: true,
  },
  {
    id: "queso-manchego-kg",
    name: "Queso Manchego Artesanal",
    price: 320,
    category: "lacteos-huevos",
    subcategory: "quesos",
    aisle: "Pasillo 4",
    image: "https://via.placeholder.com/400x300/f3f4f6/9ca3af?text=Queso+Manchego",
    description: "Queso manchego artesanal, precio por kg",
    inStock: true,
    stock: 15, // kg disponibles
    brand: "Lácteos Artesanales",
    tags: ["queso", "manchego", "artesanal", "kg"],
    rating: 4.8,
    reviewCount: 187,
    deliveryTime: "15-20 min",
    unit: "kg",
    sellByWeight: true,
  },
];

// Función para obtener productos balanceados (sin productos de prueba básicos)
export const getBalancedProducts = (): Product[] => {
  return enhancedTestProducts;
};

// Función para obtener productos por unidad de venta
export const getProductsByUnit = (unit: string): Product[] => {
  return enhancedTestProducts.filter(product => product.unit === unit);
};

// Función para obtener productos vendidos por peso
export const getWeightBasedProducts = (): Product[] => {
  return enhancedTestProducts.filter(product => product.sellByWeight === true);
};

// Función para calcular precio por cantidad/peso
export const calculatePrice = (product: Product, quantity: number): number => {
  if (product.sellByWeight) {
    // Para productos por peso, quantity representa kg o gramos
    if (product.unit === "gramo") {
      return (product.price * quantity) / 1000; // precio por gramo
    }
    return product.price * quantity; // precio por kg
  }
  return product.price * quantity; // precio por pieza/paquete
};

// Función para formatear unidad de venta
export const formatUnit = (product: Product, quantity: number): string => {
  if (product.sellByWeight) {
    if (product.unit === "gramo" && quantity >= 1000) {
      return `${(quantity / 1000).toFixed(1)} kg`;
    }
    return `${quantity} ${product.unit}`;
  }
  return quantity === 1 ? `${quantity} ${product.unit}` : `${quantity} ${product.unit}s`;
};
