import { Product } from "./data";

// Productos de prueba para validar funcionalidad del carrito
export const testProducts: Product[] = [
  // FRUTAS Y VERDURAS - Weight-based products
  {
    id: "test-manzanas-peso",
    name: "🍎 Manzanas Red Delicious",
    price: 45.90, // precio por kg
    category: "frutas-verduras",
    subcategory: "frutas-frescas",
    image: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=400&q=80",
    description: "Manzanas frescas y crujientes, venta por peso",
    inStock: true,
    stock: 50,
    unit: "kg",
    sellByWeight: true,
    tags: ["frutas", "fresco", "peso"],
    rating: 4.5,
    reviewCount: 89,
    deliveryTime: "Hoy mismo",
  },
  {
    id: "test-tomates-peso",
    name: "🍅 Tomates Riñón",
    price: 28.50, // precio por kg
    category: "frutas-verduras",
    subcategory: "verduras",
    image: "https://images.unsplash.com/photo-1546470427-e9cb45975d17?auto=format&fit=crop&w=400&q=80",
    description: "Tomates frescos y jugosos, ideales para ensaladas",
    inStock: true,
    stock: 30,
    unit: "kg",
    sellByWeight: true,
    tags: ["verduras", "fresco", "peso"],
    rating: 4.3,
    reviewCount: 156,
    deliveryTime: "Hoy mismo",
  },
  {
    id: "test-platanos-pieza",
    name: "🍌 Plátanos Tabasco",
    price: 3.50,
    category: "frutas-verduras",
    subcategory: "frutas-frescas",
    image: "https://images.unsplash.com/photo-1528825871115-3581a5387919?auto=format&fit=crop&w=400&q=80",
    description: "Plátanos dulces y maduros, venta por pieza",
    inStock: true,
    stock: 200,
    unit: "pieza",
    sellByWeight: false,
    tags: ["frutas", "dulce", "pieza"],
    rating: 4.7,
    reviewCount: 234,
    deliveryTime: "Hoy mismo",
  },

  // PANADERÍA BIMBO - Piece-based products
  {
    id: "test-pan-bimbo",
    name: "🍞 Pan Bimbo Blanco Grande",
    price: 32.50,
    category: "panaderia-bimbo",
    subcategory: "pan-de-caja",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=400&q=80",
    description: "Pan de caja blanco, 680g",
    inStock: true,
    stock: 45,
    unit: "pieza",
    sellByWeight: false,
    brand: "Bimbo",
    tags: ["panaderia", "bimbo", "basico"],
    rating: 4.4,
    reviewCount: 567,
    deliveryTime: "Hoy mismo",
  },
  {
    id: "test-gansito-bimbo",
    name: "🧁 Gansito Bimbo",
    price: 14.50,
    category: "panaderia-bimbo",
    subcategory: "pasteles-bimbo",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=400&q=80",
    description: "Delicioso pastelito relleno de mermelada",
    inStock: true,
    stock: 80,
    unit: "pieza",
    sellByWeight: false,
    brand: "Bimbo",
    tags: ["dulce", "bimbo", "snack"],
    rating: 4.8,
    reviewCount: 890,
    deliveryTime: "Hoy mismo",
  },

  // CARNICERÍA - Weight-based products
  {
    id: "test-carne-res",
    name: "🥩 Carne de Res para Asar",
    price: 189.90, // precio por kg
    category: "carniceria-cremeria",
    subcategory: "carnes-rojas",
    image: "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?auto=format&fit=crop&w=400&q=80",
    description: "Carne fresca de res, corte especial para asar",
    inStock: true,
    stock: 25,
    unit: "kg",
    sellByWeight: true,
    tags: ["carne", "res", "fresco", "peso"],
    rating: 4.6,
    reviewCount: 123,
    deliveryTime: "Hoy mismo",
  },
  {
    id: "test-pollo-entero",
    name: "🐔 Pollo Entero",
    price: 85.50, // precio por kg
    category: "carniceria-cremeria",
    subcategory: "aves",
    image: "https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=400&q=80",
    description: "Pollo fresco entero, aproximadamente 1.5kg",
    inStock: true,
    stock: 20,
    unit: "kg",
    sellByWeight: true,
    tags: ["pollo", "ave", "fresco", "peso"],
    rating: 4.5,
    reviewCount: 78,
    deliveryTime: "Hoy mismo",
  },

  // LÁCTEOS - Piece-based products
  {
    id: "test-leche-lala",
    name: "🥛 Leche Lala Entera 1L",
    price: 24.50,
    category: "lacteos-huevos",
    subcategory: "leche",
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=400&q=80",
    description: "Leche entera pasteurizada, 1 litro",
    inStock: true,
    stock: 60,
    unit: "litro",
    sellByWeight: false,
    brand: "Lala",
    tags: ["lacteos", "leche", "entera"],
    rating: 4.3,
    reviewCount: 345,
    deliveryTime: "Hoy mismo",
  },
  {
    id: "test-queso-oaxaca",
    name: "🧀 Queso Oaxaca",
    price: 95.00, // precio por kg
    category: "lacteos-huevos",
    subcategory: "quesos",
    image: "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?auto=format&fit=crop&w=400&q=80",
    description: "Queso Oaxaca fresco, venta por peso",
    inStock: true,
    stock: 15,
    unit: "kg",
    sellByWeight: true,
    tags: ["queso", "oaxaca", "peso"],
    rating: 4.7,
    reviewCount: 156,
    deliveryTime: "Hoy mismo",
  },

  // CONGELADOS - Piece-based products
  {
    id: "test-helado-haagen",
    name: "🍦 Helado Häagen-Dazs Vainilla",
    price: 85.50,
    category: "congelados",
    subcategory: "helados-paletas",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=400&q=80",
    description: "Helado premium sabor vainilla, 473ml",
    inStock: true,
    stock: 25,
    unit: "pieza",
    sellByWeight: false,
    brand: "Häagen-Dazs",
    tags: ["helado", "premium", "congelado"],
    rating: 4.9,
    reviewCount: 234,
    deliveryTime: "Hoy mismo",
  },

  // ABARROTES - Piece-based products
  {
    id: "test-arroz-verde-valle",
    name: "🍚 Arroz Verde Valle 1kg",
    price: 28.90,
    category: "abarrotes-basicos",
    subcategory: "arroz-granos",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=400&q=80",
    description: "Arroz blanco de grano largo, paquete de 1kg",
    inStock: true,
    stock: 40,
    unit: "paquete",
    sellByWeight: false,
    brand: "Verde Valle",
    tags: ["arroz", "basico", "despensa"],
    rating: 4.4,
    reviewCount: 567,
    deliveryTime: "Hoy mismo",
  },

  // PRODUCTOS CON OFERTAS Y ESTADOS ESPECIALES
  {
    id: "test-producto-stock-bajo",
    name: "⚠️ Aceite La Costeña - Últimas 2 piezas",
    price: 45.90,
    category: "aceites-condimentos",
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=400&q=80",
    description: "Aceite vegetal comestible, 1 litro - Stock limitado",
    inStock: true,
    stock: 2,
    unit: "botella",
    sellByWeight: false,
    brand: "La Costeña",
    tags: ["aceite", "stock-bajo", "urgente"],
    rating: 4.2,
    reviewCount: 89,
    deliveryTime: "Hoy mismo",
  },
  {
    id: "test-producto-agotado",
    name: "❌ Papel Higiénico Suave - Agotado",
    price: 65.50,
    category: "limpieza-hogar",
    image: "https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?auto=format&fit=crop&w=400&q=80",
    description: "Papel higiénico suave, paquete de 12 rollos",
    inStock: false,
    stock: 0,
    unit: "paquete",
    sellByWeight: false,
    brand: "Suave",
    tags: ["papel", "agotado", "higiene"],
    rating: 4.0,
    reviewCount: 234,
    deliveryTime: "No disponible",
  },
  {
    id: "test-producto-oferta",
    name: "🔥 Coca-Cola 2L - ¡OFERTA!",
    price: 28.90,
    originalPrice: 35.50,
    category: "bebidas-refrescos",
    image: "https://images.unsplash.com/photo-1554866585-cd94860890b7?auto=format&fit=crop&w=400&q=80",
    description: "Refresco de cola, 2 litros - Precio especial",
    inStock: true,
    stock: 150,
    unit: "botella",
    sellByWeight: false,
    brand: "Coca-Cola",
    tags: ["refresco", "oferta", "descuento"],
    rating: 4.8,
    reviewCount: 1234,
    deliveryTime: "Hoy mismo",
    isOffer: true,
  },
  {
    id: "test-producto-nuevo",
    name: "✨ Yogurt Griego Danone - ¡NUEVO!",
    price: 42.50,
    category: "lacteos-huevos",
    subcategory: "yogurt-fermentados",
    image: "https://images.unsplash.com/photo-1571212515416-ff789e2ec29a?auto=format&fit=crop&w=400&q=80",
    description: "Yogurt griego natural, 1kg - Producto recién llegado",
    inStock: true,
    stock: 35,
    unit: "pieza",
    sellByWeight: false,
    brand: "Danone",
    tags: ["yogurt", "nuevo", "griego"],
    rating: 4.9,
    reviewCount: 45,
    deliveryTime: "Hoy mismo",
    isNew: true,
  },
];

// Función para agregar productos de prueba en desarrollo
export const addTestProducts = (): Product[] => {
  if (process.env.NODE_ENV === "development") {
    console.log("🧪 Agregando productos de prueba para desarrollo");
    return testProducts;
  }
  return [];
};
