import { Product } from "./data";

// Productos de prueba para validar funcionalidad del carrito
export const testProducts: Product[] = [
  // FRUTAS Y VERDURAS - Weight-based products
  {
    id: "test-manzanas-peso",
    name: "🍎 Manzanas Red Delicious",
    price: 45.90, // precio por kg
    category: "frutas-verduras",
    subcategory: "frutas-frescas",
    image: "https://images.unsplash.com/photo-1560806887-1e4cd0b6cbd6?auto=format&fit=crop&w=400&q=80",
    description: "Manzanas frescas y crujientes, venta por peso",
    inStock: true,
    stock: 50,
    unit: "kg",
    sellByWeight: true,
    tags: ["frutas", "fresco", "peso"],
    rating: 4.5,
    reviewCount: 89,
    deliveryTime: "Hoy mismo",
  },
  {
    id: "test-tomates-peso",
    name: "🍅 Tomates Riñón",
    price: 28.50, // precio por kg
    category: "frutas-verduras",
    subcategory: "verduras",
    image: "https://images.unsplash.com/photo-1546470427-e9cb45975d17?auto=format&fit=crop&w=400&q=80",
    description: "Tomates frescos y jugosos, ideales para ensaladas",
    inStock: true,
    stock: 30,
    unit: "kg",
    sellByWeight: true,
    tags: ["verduras", "fresco", "peso"],
    rating: 4.3,
    reviewCount: 156,
    deliveryTime: "Hoy mismo",
  },
  {
    id: "test-platanos-pieza",
    name: "🍌 Plátanos Tabasco",
    price: 3.50,
    category: "frutas-verduras",
    subcategory: "frutas-frescas",
    image: "https://images.unsplash.com/photo-1528825871115-3581a5387919?auto=format&fit=crop&w=400&q=80",
    description: "Plátanos dulces y maduros, venta por pieza",
    inStock: true,
    stock: 200,
    unit: "pieza",
    sellByWeight: false,
    tags: ["frutas", "dulce", "pieza"],
    rating: 4.7,
    reviewCount: 234,
    deliveryTime: "Hoy mismo",
  },

  // PANADERÍA BIMBO - Piece-based products
  {
    id: "test-pan-bimbo",
    name: "🍞 Pan Bimbo Blanco Grande",
    price: 32.50,
    category: "panaderia-bimbo",
    subcategory: "pan-de-caja",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=400&q=80",
    description: "Pan de caja blanco, 680g",
    inStock: true,
    stock: 45,
    unit: "pieza",
    sellByWeight: false,
    brand: "Bimbo",
    tags: ["panaderia", "bimbo", "basico"],
    rating: 4.4,
    reviewCount: 567,
    deliveryTime: "Hoy mismo",
  },
  {
    id: "test-gansito-bimbo",
    name: "🧁 Gansito Bimbo",
    price: 14.50,
    category: "panaderia-bimbo",
    subcategory: "pasteles-bimbo",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=400&q=80",
    description: "Delicioso pastelito relleno de mermelada",
    inStock: true,
    stock: 80,
    unit: "pieza",
    sellByWeight: false,
    brand: "Bimbo",
    tags: ["dulce", "bimbo", "snack"],
    rating: 4.8,
    reviewCount: 890,
    deliveryTime: "Hoy mismo",
  },

  // CARNICERÍA - Weight-based products
  {
    id: "test-carne-res",
    name: "🥩 Carne de Res para Asar",
    price: 189.90, // precio por kg
    category: "carniceria-cremeria",
    subcategory: "carnes-rojas",
    image: "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?auto=format&fit=crop&w=400&q=80",
    description: "Carne fresca de res, corte especial para asar",
    inStock: true,
    stock: 25,
    unit: "kg",
    sellByWeight: true,
    tags: ["carne", "res", "fresco", "peso"],
    rating: 4.6,
    reviewCount: 123,
    deliveryTime: "Hoy mismo",
  },
  {
    id: "test-pollo-entero",
    name: "🐔 Pollo Entero",
    price: 85.50, // precio por kg
    category: "carniceria-cremeria",
    subcategory: "aves",
    image: "https://images.unsplash.com/photo-1604503468506-a8da13d82791?auto=format&fit=crop&w=400&q=80",
    description: "Pollo fresco entero, aproximadamente 1.5kg",
    inStock: true,
    stock: 20,
    unit: "kg",
    sellByWeight: true,
    tags: ["pollo", "ave", "fresco", "peso"],
    rating: 4.5,
    reviewCount: 78,
    deliveryTime: "Hoy mismo",
  },

  // LÁCTEOS - Piece-based products
  {
    id: "test-leche-lala",
    name: "🥛 Leche Lala Entera 1L",
    price: 24.50,
    category: "lacteos-huevos",
    subcategory: "leche",
    image: "https://images.unsplash.com/photo-1556909114-f6e7ad7d3136?auto=format&fit=crop&w=400&q=80",
    description: "Leche entera pasteurizada, 1 litro",
    inStock: true,
    stock: 60,
    unit: "litro",
    sellByWeight: false,
    brand: "Lala",
    tags: ["lacteos", "leche", "entera"],
    rating: 4.3,
    reviewCount: 345,
    deliveryTime: "Hoy mismo",
  },
  {
    id: "test-queso-oaxaca",
    name: "🧀 Queso Oaxaca",
    price: 95.00, // precio por kg
    category: "lacteos-huevos",
    subcategory: "quesos",
    image: "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?auto=format&fit=crop&w=400&q=80",
    description: "Queso Oaxaca fresco, venta por peso",
    inStock: true,
    stock: 15,
    unit: "kg",
    sellByWeight: true,
    tags: ["queso", "oaxaca", "peso"],
    rating: 4.7,
    reviewCount: 156,
    deliveryTime: "Hoy mismo",
  },

  // CONGELADOS - Piece-based products
  {
    id: "test-helado-haagen",
    name: "🍦 Helado Häagen-Dazs Vainilla",
    price: 85.50,
    category: "congelados",
    subcategory: "helados-paletas",
    image: "https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=400&q=80",
    description: "Helado premium sabor vainilla, 473ml",
    inStock: true,
    stock: 25,
    unit: "pieza",
    sellByWeight: false,
    brand: "Häagen-Dazs",
    tags: ["helado", "premium", "congelado"],
    rating: 4.9,
    reviewCount: 234,
    deliveryTime: "Hoy mismo",
  },

  // ABARROTES - Piece-based products
  {
    id: "test-arroz-verde-valle",
    name: "🍚 Arroz Verde Valle 1kg",
    price: 28.90,
    category: "abarrotes-basicos",
    subcategory: "arroz-granos",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=400&q=80",
    description: "Arroz blanco de grano largo, paquete de 1kg",
    inStock: true,
    stock: 40,
    unit: "paquete",
    sellByWeight: false,
    brand: "Verde Valle",
    tags: ["arroz", "basico", "despensa"],
    rating: 4.4,
    reviewCount: 567,
    deliveryTime: "Hoy mismo",
  },

  // PRODUCTOS CON OFERTAS Y ESTADOS ESPECIALES
  {
    id: "test-producto-stock-bajo",
    name: "⚠️ Aceite La Costeña - Últimas 2 piezas",
    price: 45.90,
    category: "aceites-condimentos",
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=400&q=80",
    description: "Aceite vegetal comestible, 1 litro - Stock limitado",
    inStock: true,
    stock: 2,
    unit: "botella",
    sellByWeight: false,
    brand: "La Costeña",
    tags: ["aceite", "stock-bajo", "urgente"],
    rating: 4.2,
    reviewCount: 89,
    deliveryTime: "Hoy mismo",
  },
  {
    id: "test-producto-agotado",
    name: "❌ Papel Higiénico Suave - Agotado",
    price: 65.50,
    category: "limpieza-hogar",
    image: "https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?auto=format&fit=crop&w=400&q=80",
    description: "Papel higiénico suave, paquete de 12 rollos",
    inStock: false,
    stock: 0,
    unit: "paquete",
    sellByWeight: false,
    brand: "Suave",
    tags: ["papel", "agotado", "higiene"],
    rating: 4.0,
    reviewCount: 234,
    deliveryTime: "No disponible",
  },
  {
    id: "test-producto-oferta",
    name: "🔥 Coca-Cola 2L - ¡OFERTA!",
    price: 28.90,
    originalPrice: 35.50,
    category: "bebidas-refrescos",
    image: "https://images.unsplash.com/photo-1554866585-cd94860890b7?auto=format&fit=crop&w=400&q=80",
    description: "Refresco de cola, 2 litros - Precio especial",
    inStock: true,
    stock: 150,
    unit: "botella",
    sellByWeight: false,
    brand: "Coca-Cola",
    tags: ["refresco", "oferta", "descuento"],
    rating: 4.8,
    reviewCount: 1234,
    deliveryTime: "Hoy mismo",
    isOffer: true,
  },
  {
    id: "test-producto-nuevo",
    name: "✨ Yogurt Griego Danone - ¡NUEVO!",
    price: 42.50,
    category: "lacteos-huevos",
    subcategory: "yogurt-fermentados",
    image: "https://images.unsplash.com/photo-1571212515416-ff789e2ec29a?auto=format&fit=crop&w=400&q=80",
    description: "Yogurt griego natural, 1kg - Producto recién llegado",
    inStock: true,
    stock: 35,
    unit: "pieza",
    sellByWeight: false,
    brand: "Danone",
    tags: ["yogurt", "nuevo", "griego"],
    rating: 4.9,
    reviewCount: 45,
    deliveryTime: "Hoy mismo",
    isNew: true,
  },

  // PRODUCTOS ADICIONALES CON OFERTAS
  {
    id: "test-pan-integral-oferta",
    name: "🔥 Pan Integral Bimbo - ¡50% OFF!",
    price: 16.25,
    originalPrice: 32.50,
    category: "panaderia-bimbo",
    subcategory: "pan-de-caja",
    image: "https://images.unsplash.com/photo-1509440159596-0249088772ff?auto=format&fit=crop&w=400&q=80",
    description: "Pan integral con fibra, precio especial",
    inStock: true,
    stock: 60,
    unit: "pieza",
    sellByWeight: false,
    brand: "Bimbo",
    tags: ["pan", "integral", "oferta", "fibra"],
    rating: 4.6,
    reviewCount: 234,
    deliveryTime: "Hoy mismo",
    isOffer: true,
  },
  {
    id: "test-atun-dolores-oferta",
    name: "🔥 Atún Dolores en Agua - Pack 3",
    price: 45.90,
    originalPrice: 65.70,
    category: "enlatados-conservas",
    subcategory: "atun-sardinas",
    image: "https://images.unsplash.com/photo-1553909489-cd47e0ef937f?auto=format&fit=crop&w=400&q=80",
    description: "Pack de 3 latas de atún en agua - Ahorra 30%",
    inStock: true,
    stock: 40,
    unit: "paquete",
    sellByWeight: false,
    brand: "Dolores",
    tags: ["atun", "pack", "oferta", "proteina"],
    rating: 4.7,
    reviewCount: 456,
    deliveryTime: "Hoy mismo",
    isOffer: true,
  },
  {
    id: "test-detergente-ace-oferta",
    name: "🔥 Detergente ACE 3kg - ¡MEGA OFERTA!",
    price: 89.90,
    originalPrice: 125.00,
    category: "limpieza-hogar",
    subcategory: "detergentes",
    image: "https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?auto=format&fit=crop&w=400&q=80",
    description: "Detergente en polvo para ropa, formato familiar",
    inStock: true,
    stock: 25,
    unit: "paquete",
    sellByWeight: false,
    brand: "ACE",
    tags: ["detergente", "limpieza", "oferta", "familiar"],
    rating: 4.4,
    reviewCount: 567,
    deliveryTime: "Hoy mismo",
    isOffer: true,
  },
  {
    id: "test-jabon-zote-pack",
    name: "🔥 Jabón Zote Rosa - Pack 5 piezas",
    price: 24.90,
    originalPrice: 35.00,
    category: "limpieza-hogar",
    subcategory: "jabones",
    image: "https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?auto=format&fit=crop&w=400&q=80",
    description: "Pack de 5 jabones Zote rosa de 200g c/u",
    inStock: true,
    stock: 80,
    unit: "paquete",
    sellByWeight: false,
    brand: "Zote",
    tags: ["jabon", "zote", "pack", "rosa"],
    rating: 4.8,
    reviewCount: 789,
    deliveryTime: "Hoy mismo",
    isOffer: true,
  },
  {
    id: "test-frijoles-bayos-2kg",
    name: "🔥 Frijoles Bayos La Costeña 2kg - OFERTA",
    price: 45.90,
    originalPrice: 58.90,
    category: "abarrotes-basicos",
    subcategory: "frijoles-legumbres",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=400&q=80",
    description: "Frijoles bayos premium, costal de 2kg",
    inStock: true,
    stock: 35,
    unit: "paquete",
    sellByWeight: false,
    brand: "La Costeña",
    tags: ["frijoles", "bayos", "costal", "oferta"],
    rating: 4.5,
    reviewCount: 345,
    deliveryTime: "Hoy mismo",
    isOffer: true,
  },
  {
    id: "test-aceite-123-oferta",
    name: "🔥 Aceite 123 - 1L + 500ml GRATIS",
    price: 42.90,
    originalPrice: 65.00,
    category: "aceites-condimentos",
    subcategory: "aceites-vegetales",
    image: "https://images.unsplash.com/photo-1474979266404-7eaacbcd87c5?auto=format&fit=crop&w=400&q=80",
    description: "Aceite vegetal comestible, pack promocional",
    inStock: true,
    stock: 50,
    unit: "botella",
    sellByWeight: false,
    brand: "123",
    tags: ["aceite", "promocion", "gratis", "cocina"],
    rating: 4.3,
    reviewCount: 234,
    deliveryTime: "Hoy mismo",
    isOffer: true,
  },
  {
    id: "test-salchichas-fud-oferta",
    name: "🔥 Salchichas FUD - Pack 2x1",
    price: 28.90,
    originalPrice: 42.50,
    category: "carniceria-cremeria",
    subcategory: "embutidos",
    image: "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?auto=format&fit=crop&w=400&q=80",
    description: "Salchichas de pavo, pack 2 paquetes por el precio de 1",
    inStock: true,
    stock: 45,
    unit: "paquete",
    sellByWeight: false,
    brand: "FUD",
    tags: ["salchichas", "pavo", "2x1", "oferta"],
    rating: 4.6,
    reviewCount: 178,
    deliveryTime: "Hoy mismo",
    isOffer: true,
  },
  {
    id: "test-galletas-emperador-oferta",
    name: "🔥 Galletas Emperador - 30% Descuento",
    price: 18.90,
    originalPrice: 27.00,
    category: "snacks-dulces",
    subcategory: "galletas-cookies",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=400&q=80",
    description: "Galletas de chocolate con crema, paquete familiar",
    inStock: true,
    stock: 70,
    unit: "paquete",
    sellByWeight: false,
    brand: "Gamesa",
    tags: ["galletas", "chocolate", "crema", "oferta"],
    rating: 4.7,
    reviewCount: 456,
    deliveryTime: "Hoy mismo",
    isOffer: true,
  },

  // PRODUCTOS ECONÓMICOS BAJO $20
  {
    id: "test-sal-refinada",
    name: "🧂 Sal La Fina 1kg",
    price: 12.50,
    category: "abarrotes-basicos",
    subcategory: "sal-especias",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=400&q=80",
    description: "Sal de mesa refinada, paquete de 1kg",
    inStock: true,
    stock: 100,
    unit: "paquete",
    sellByWeight: false,
    brand: "La Fina",
    tags: ["sal", "cocina", "basico", "economico"],
    rating: 4.2,
    reviewCount: 234,
    deliveryTime: "Hoy mismo",
  },
  {
    id: "test-azucar-estandar",
    name: "🍯 Azúcar Estándar 1kg",
    price: 18.90,
    category: "abarrotes-basicos",
    subcategory: "azucar-endulzantes",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=400&q=80",
    description: "Azúcar blanca refinada, bolsa de 1kg",
    inStock: true,
    stock: 80,
    unit: "paquete",
    sellByWeight: false,
    brand: "Estándar",
    tags: ["azucar", "dulce", "basico", "economico"],
    rating: 4.1,
    reviewCount: 456,
    deliveryTime: "Hoy mismo",
  },
  {
    id: "test-cafe-nescafe-economico",
    name: "☕ Café Nescafé Clásico 90g",
    price: 19.90,
    category: "bebidas-refrescos",
    subcategory: "cafes-tes",
    image: "https://images.unsplash.com/photo-1554866585-cd94860890b7?auto=format&fit=crop&w=400&q=80",
    description: "Café soluble instantáneo, frasco pequeño",
    inStock: true,
    stock: 65,
    unit: "frasco",
    sellByWeight: false,
    brand: "Nescafé",
    tags: ["cafe", "soluble", "economico", "instantaneo"],
    rating: 4.5,
    reviewCount: 567,
    deliveryTime: "Hoy mismo",
  },
  {
    id: "test-papel-higienico-petalo",
    name: "🧻 Papel Higiénico Pétalo 4 rollos",
    price: 16.90,
    category: "limpieza-hogar",
    subcategory: "papel-higienico",
    image: "https://images.unsplash.com/photo-1584551246679-0daf3d275d0f?auto=format&fit=crop&w=400&q=80",
    description: "Papel higiénico suave, paquete de 4 rollos",
    inStock: true,
    stock: 120,
    unit: "paquete",
    sellByWeight: false,
    brand: "Pétalo",
    tags: ["papel", "higienico", "suave", "economico"],
    rating: 4.3,
    reviewCount: 789,
    deliveryTime: "Hoy mismo",
  },
  {
    id: "test-pasta-la-moderna",
    name: "🍝 Pasta La Moderna Coditos 200g",
    price: 15.50,
    category: "abarrotes-basicos",
    subcategory: "pasta-fideos",
    image: "https://images.unsplash.com/photo-1586201375761-83865001e31c?auto=format&fit=crop&w=400&q=80",
    description: "Pasta de trigo, coditos medianos",
    inStock: true,
    stock: 95,
    unit: "paquete",
    sellByWeight: false,
    brand: "La Moderna",
    tags: ["pasta", "coditos", "trigo", "economico"],
    rating: 4.4,
    reviewCount: 345,
    deliveryTime: "Hoy mismo",
  },

  // PRODUCTOS ADICIONALES POR GRAMOS
  {
    id: "test-queso-panela-gramos",
    name: "🧀 Queso Panela Fresco",
    price: 0.12, // precio por gramo ($120 por kg)
    category: "lacteos-huevos",
    subcategory: "quesos",
    image: "https://images.unsplash.com/photo-1486297678162-eb2a19b0a32d?auto=format&fit=crop&w=400&q=80",
    description: "Queso panela fresco artesanal, venta por gramos",
    inStock: true,
    stock: 5000, // 5kg en gramos
    unit: "gramo",
    sellByWeight: true,
    tags: ["queso", "panela", "fresco", "gramos"],
    rating: 4.6,
    reviewCount: 89,
    deliveryTime: "Hoy mismo",
  },
  {
    id: "test-jamon-serrano-gramos",
    name: "🍖 Jamón Serrano Premium",
    price: 0.08, // precio por gramo ($80 por kg)
    category: "carniceria-cremeria",
    subcategory: "carnes-frias",
    image: "https://images.unsplash.com/photo-1607623814075-e51df1bdc82f?auto=format&fit=crop&w=400&q=80",
    description: "Jamón serrano curado, corte al momento",
    inStock: true,
    stock: 2000, // 2kg en gramos
    unit: "gramo",
    sellByWeight: true,
    tags: ["jamon", "serrano", "premium", "gramos"],
    rating: 4.8,
    reviewCount: 156,
    deliveryTime: "Hoy mismo",
  },
  {
    id: "test-nueces-gramos",
    name: "🥜 Nueces de Castilla",
    price: 0.15, // precio por gramo ($150 por kg)
    category: "snacks-dulces",
    subcategory: "frutos-secos",
    image: "https://images.unsplash.com/photo-1578985545062-69928b1d9587?auto=format&fit=crop&w=400&q=80",
    description: "Nueces de castilla natural, venta por gramos",
    inStock: true,
    stock: 1500, // 1.5kg en gramos
    unit: "gramo",
    sellByWeight: true,
    tags: ["nueces", "frutos-secos", "natural", "gramos"],
    rating: 4.7,
    reviewCount: 234,
    deliveryTime: "Hoy mismo",
  },
];

// Función para agregar productos de prueba en desarrollo
export const addTestProducts = (): Product[] => {
  if (process.env.NODE_ENV === "development") {
    console.log("🧪 Agregando productos de prueba para desarrollo");
    return testProducts;
  }
  return [];
};
